[project]
name = "keyring-test"
version = "0.1.0"
description = "Ein einfaches Testprojekt für das Python-Paket keyring"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyring>=25.6.0",
]